name: Benchmarks
on: workflow_dispatch
jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - arch: amd64
          - arch: x86
      fail-fast: false
    env:
      CMAKE_GENERATOR: Ninja
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
        with:
          arch: ${{ matrix.arch }}
      - name: Install prerequisites
        run: |
          cinst --no-progress ninja
      - name: Run CMake
        run: |
          cmake -S . -B build `
            -DCMAKE_BUILD_TYPE=Release `
            -DSEIR_AUDIO=ON `
            -DSEIR_BENCHMARKS=ON `
            -DSEIR_IMAGE=ON `
            -DSEIR_STATIC_RUNTIME=ON
      - name: Build
        run: |
          cmake --build build
      - name: Run benchmarks
        run: |
          build\libs\audio\benchmarks\seir_audio_benchmarks.exe
  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cxx: g++-10
          - cxx: clang++-12
      fail-fast: false
    env:
      CXX: ${{ matrix.cxx }}
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev ninja-build
      - name: Run CMake
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DSEIR_AUDIO=ON \
            -DSEIR_BENCHMARKS=ON \
            -DSEIR_IMAGE=ON
      - name: Build
        run: |
          cmake --build build
      - name: Run benchmarks
        run: |
          build/libs/audio/benchmarks/seir_audio_benchmarks
