name: Benchmarks
on: workflow_dispatch
jobs:
  windows:
    name: Windows
    runs-on: windows-2022
    strategy:
      matrix:
        include:
          - arch: amd64
          - arch: x86
      fail-fast: false
    env:
      CMAKE_GENERATOR: Ninja
    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
        with:
          arch: ${{ matrix.arch }}
      - name: Install prerequisites
        run: |
          cinst --no-progress ninja
      - name: Run CMake
        run: |
          cmake -S . -B build `
            -DCMAKE_BUILD_TYPE=Release `
            -DSEIR_BENCHMARKS=ON `
            -DSEIR_STATIC_RUNTIME=ON `
            -DSEIR_APP=OFF `
            -DSEIR_DATA=OFF `
            -DSEIR_GRAPHICS=OFF `
            -DSEIR_GUI=OFF `
            -DSEIR_IMAGE=OFF `
            -DSEIR_MATH=OFF `
            -DSEIR_RENDERER=OFF `
            -DSEIR_SERIALIZATION=OFF `
            -DSEIR_SYNTH=OFF `
            -DSEIR_U8MAIN=OFF `
            -DSEIR_UTILS=OFF
      - name: Build
        run: |
          cmake --build build
      - name: Run benchmarks
        run: |
          build\libs\audio\benchmarks\seir_audio_benchmarks.exe
  linux:
    name: Linux
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - cc: gcc-14
            cxx: g++-14
          - cc: clang-18
            cxx: clang++-18
      fail-fast: false
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
    steps:
      - uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev ninja-build
      - name: Run CMake
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DSEIR_BENCHMARKS=ON \
            -DSEIR_STATIC_RUNTIME=ON \
            -DSEIR_APP=OFF \
            -DSEIR_DATA=OFF \
            -DSEIR_GRAPHICS=OFF \
            -DSEIR_GUI=OFF \
            -DSEIR_IMAGE=OFF \
            -DSEIR_MATH=OFF \
            -DSEIR_RENDERER=OFF \
            -DSEIR_SERIALIZATION=OFF \
            -DSEIR_SYNTH=OFF \
            -DSEIR_U8MAIN=OFF \
            -DSEIR_UTILS=OFF
      - name: Build
        run: |
          cmake --build build
      - name: Run benchmarks
        run: |
          build/libs/audio/benchmarks/seir_audio_benchmarks
