name: Linux
on:
  push:
    paths-ignore:
      - '.clang-tidy'
      - 'LICENSE'
      - 'README.md'
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - cc: gcc-13
            cxx: g++-13
            config: Release
          - cc: gcc-13
            cxx: g++-13
            config: Debug
          - cc: clang-15
            cxx: clang++-15
            config: Release
          - cc: clang-15
            cxx: clang++-15
            config: Debug
      fail-fast: false
    env:
      CC: ${{ matrix.cxx }}
      CFLAGS: -fsanitize=address -fsanitize=undefined -fno-sanitize=nonnull-attribute
      CXX: ${{ matrix.cxx }}
      CXXFLAGS: -fsanitize=address -fsanitize=undefined -fno-sanitize=nonnull-attribute
      LDFLAGS: -fsanitize=address -fsanitize=undefined
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/build/_SeirDownloads
          key: linux-${{ hashFiles('cmake/SeirPackages/*.cmake') }}
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libvorbis-dev ninja-build
      - name: Run CMake
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/install" \
            -DSEIR_3RDPARTY_SKIP="freetype;jpeg;ogg;vorbis;zlib;zstd" \
            -DSEIR_AUDIO_OGGVORBIS=ON \
            -DSEIR_AUDIO_WAV=ON \
            -DSEIR_BENCHMARKS=ON \
            -DSEIR_COMPRESSION_ZLIB=ON \
            -DSEIR_COMPRESSION_ZSTD=OFF \
            -DSEIR_EXAMPLES=ON \
            -DSEIR_IMAGE_BMP=ON \
            -DSEIR_IMAGE_ICO=ON \
            -DSEIR_IMAGE_JPEG=ON \
            -DSEIR_IMAGE_TGA=ON \
            -DSEIR_RENDERER=Dummy \
            -DSEIR_SYNTH=ON \
            -DSEIR_TESTS=ON \
            -DSEIR_U8MAIN=ON
      - name: Build
        run: |
          cmake --build build
      - name: Run tests
        run: |
          cd build
          ASAN_OPTIONS=allocator_may_return_null=1 ctest --verbose
      - name: Check exports
        run: |
          cmake --build build --target install
          cmake -S cmake/test -B build.test -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DCMAKE_PREFIX_PATH="${{ github.workspace }}/install"
          cmake --build build.test
  coverage:
    name: Coverage
    runs-on: ubuntu-22.04
    env:
      CC: gcc-13
      CFLAGS: --coverage
      CXX: g++-13
      CXXFLAGS: --coverage
      LDFLAGS: --coverage
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/build/_SeirDownloads
          key: linux-${{ hashFiles('cmake/SeirPackages/*.cmake') }}
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libvorbis-dev ninja-build
      - name: Run CMake
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DSEIR_3RDPARTY_SKIP="freetype;jpeg;ogg;vorbis;zlib;zstd" \
            -DSEIR_AUDIO_OGGVORBIS=ON \
            -DSEIR_AUDIO_WAV=ON \
            -DSEIR_COMPRESSION_ZLIB=ON \
            -DSEIR_COMPRESSION_ZSTD=OFF \
            -DSEIR_IMAGE_BMP=ON \
            -DSEIR_IMAGE_ICO=ON \
            -DSEIR_IMAGE_JPEG=ON \
            -DSEIR_IMAGE_TGA=ON \
            -DSEIR_RENDERER=Dummy \
            -DSEIR_SYNTH=ON \
            -DSEIR_TESTS=ON \
            -DSEIR_U8MAIN=ON
      - name: Build
        run: |
          cmake --build build
      - name: Run tests
        run: |
          cd build
          ctest --verbose
      - name: Upload coverage reports
        run: |
          pip install --user codecov
          codecov --gcov-root "${{ github.workspace }}/build" --gcov-exec gcov-13 --gcov-args "-s ${{ github.workspace }}"
