name: Linux (GCC)
on:
  push:
    paths-ignore:
      - '.clang-tidy'
      - 'LICENSE'
      - 'README.md'
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - cc: gcc-14
            cxx: g++-14
            config: Release
          - cc: gcc-14
            cxx: g++-14
            config: Debug
      fail-fast: false
    env:
      CC: ${{ matrix.cc }}
      CFLAGS: -fsanitize=address -fsanitize=undefined -fno-sanitize=nonnull-attribute
      CXX: ${{ matrix.cxx }}
      CXXFLAGS: -fsanitize=address -fsanitize=undefined -fno-sanitize=nonnull-attribute
      LDFLAGS: -fsanitize=address -fsanitize=undefined
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/build/_SeirDownloads
          key: linux-${{ hashFiles('cmake/SeirPackages/*.cmake') }}
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libfreetype-dev libjpeg-dev libvorbis-dev ninja-build
      - name: Run CMake
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/install" \
            -DSEIR_3RDPARTY_SKIP="freetype;jpeg;ogg;vorbis;zlib;zstd" \
            -DSEIR_AUDIO_OGGVORBIS=ON \
            -DSEIR_AUDIO_WAV=ON \
            -DSEIR_BENCHMARKS=ON \
            -DSEIR_COMPRESSION_ZLIB=ON \
            -DSEIR_COMPRESSION_ZSTD=OFF \
            -DSEIR_EXAMPLES=ON \
            -DSEIR_IMAGE_BMP=ON \
            -DSEIR_IMAGE_DDS=ON \
            -DSEIR_IMAGE_ICO=ON \
            -DSEIR_IMAGE_JPEG=ON \
            -DSEIR_IMAGE_PNG=ON \
            -DSEIR_IMAGE_TGA=ON \
            -DSEIR_IMAGE_WEBP=ON \
            -DSEIR_RENDERER_BACKEND= \
            -DSEIR_TESTS=ON
      - name: Build
        run: |
          cmake --build build
      - name: Run tests
        run: |
          ASAN_OPTIONS=allocator_may_return_null=1 ctest --verbose --test-dir build
      - name: Build usage examples
        run: |
          cmake -S examples/usage/cmake_fetchcontent -B build.cmake_fetchcontent -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DREPLACE_WITH_COMMIT_HASH=${{ github.sha }}
          cmake --build build.cmake_fetchcontent
          cmake --build build --target install
          cmake -S examples/usage/cmake_package -B build.cmake_package -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DCMAKE_PREFIX_PATH="${{ github.workspace }}/install"
          cmake --build build.cmake_package
  coverage:
    name: Coverage
    runs-on: ubuntu-24.04
    env:
      CC: gcc-14
      CFLAGS: --coverage
      CXX: g++-14
      CXXFLAGS: --coverage
      LDFLAGS: --coverage
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/build/_SeirDownloads
          key: linux-${{ hashFiles('cmake/SeirPackages/*.cmake') }}
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libfreetype-dev libjpeg-dev libvorbis-dev ninja-build
      - name: Run CMake
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DSEIR_3RDPARTY_SKIP="freetype;jpeg;ogg;vorbis;zlib;zstd" \
            -DSEIR_AUDIO_OGGVORBIS=ON \
            -DSEIR_AUDIO_WAV=ON \
            -DSEIR_COMPRESSION_ZLIB=ON \
            -DSEIR_COMPRESSION_ZSTD=OFF \
            -DSEIR_IMAGE_BMP=ON \
            -DSEIR_IMAGE_DDS=ON \
            -DSEIR_IMAGE_ICO=ON \
            -DSEIR_IMAGE_JPEG=ON \
            -DSEIR_IMAGE_PNG=ON \
            -DSEIR_IMAGE_TGA=ON \
            -DSEIR_IMAGE_WEBP=ON \
            -DSEIR_RENDERER_BACKEND= \
            -DSEIR_TESTS=ON
      - name: Build
        run: |
          cmake --build build
      - name: Run tests
        run: |
          ctest --verbose --test-dir build
      - uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          plugin: gcov
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
