name: Linux
on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
jobs:
  ci:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cxx: g++-10
            config: Release
          - cxx: g++-10
            config: Debug
          - cxx: clang++-12
            config: Release
          - cxx: clang++-12
            config: Debug
          - cxx: g++-10
            config: Debug
            mode: coverage
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build
      - name: Run CMake
        env:
          CXX: ${{ matrix.cxx }}
        run: |
          if [ "${{ matrix.mode }}" == "coverage" ]; then
            export CXXFLAGS="--coverage"
            export LDFLAGS="--coverage"
          else
            export CXXFLAGS="-fsanitize=address -fsanitize=undefined -fno-sanitize=nonnull-attribute"
            export LDFLAGS="-fsanitize=address -fsanitize=undefined"
          fi
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/install" \
            -DSEIR_TESTS=ON
      - name: Build
        run: |
          cmake --build build
          cmake --build build --target install
      - name: Run tests
        run: |
          cd build
          ASAN_OPTIONS=allocator_may_return_null=1 ctest --verbose
          cd "${{ github.workspace }}"
          cmake -S cmake/SeirExample -B build.example -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DCMAKE_PREFIX_PATH="${{ github.workspace }}/install"
          cmake --build build.example
      - name: Upload coverage reports
        if: matrix.mode == 'coverage'
        run: |
          pip install --user codecov
          codecov --gcov-root "${{ github.workspace }}/build" --gcov-exec gcov-10 --gcov-args "-s `pwd`"
