name: Linux
on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cxx: g++-10
            config: Release
          - cxx: g++-10
            config: Debug
          - cxx: clang++-12
            config: Release
          - cxx: clang++-12
            config: Debug
      fail-fast: false
    env:
      CXX: ${{ matrix.cxx }}
      CXXFLAGS: -fsanitize=address -fsanitize=undefined -fno-sanitize=nonnull-attribute
      LDFLAGS: -fsanitize=address -fsanitize=undefined
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libvorbis-dev ninja-build
      - name: Run CMake
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/install" \
            -DSEIR_AUDIO=ON \
            -DSEIR_AUDIO_AULOS=ON \
            -DSEIR_AUDIO_OGGVORBIS=ON \
            -DSEIR_AUDIO_WAV=ON \
            -DSEIR_BENCHMARKS=ON \
            -DSEIR_COMPRESSION_ZLIB=ON \
            -DSEIR_COMPRESSION_ZSTD=ON \
            -DSEIR_DATA=ON \
            -DSEIR_EXAMPLES=ON \
            -DSEIR_TESTS=ON \
            -DSEIR_U8MAIN=ON
      - name: Build
        run: |
          cmake --build build
      - name: Run tests
        run: |
          cd build
          ASAN_OPTIONS=allocator_may_return_null=1 ctest --verbose
      - name: Check exports
        run: |
          cmake --build build --target install
          cmake -S cmake/test -B build.test -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DCMAKE_PREFIX_PATH="${{ github.workspace }}/install"
          cmake --build build.test
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cxx: g++-10
          - cxx: clang++-12
      fail-fast: false
    env:
      CXX: ${{ matrix.cxx }}
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev ninja-build
      - name: Run CMake
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DSEIR_AUDIO=ON \
            -DSEIR_BENCHMARKS=ON
      - name: Build
        run: |
          cmake --build build
      - name: Run benchmarks
        run: |
          build/libs/audio/benchmarks/seir_audio_benchmarks
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    env:
      CXX: g++-10
      CXXFLAGS: --coverage
      LDFLAGS: --coverage
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libvorbis-dev ninja-build
      - name: Run CMake
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DSEIR_AUDIO=ON \
            -DSEIR_AUDIO_AULOS=ON \
            -DSEIR_AUDIO_OGGVORBIS=ON \
            -DSEIR_AUDIO_WAV=ON \
            -DSEIR_COMPRESSION_ZLIB=ON \
            -DSEIR_COMPRESSION_ZSTD=ON \
            -DSEIR_DATA=ON \
            -DSEIR_TESTS=ON \
            -DSEIR_U8MAIN=ON
      - name: Build
        run: |
          cmake --build build
      - name: Run tests
        run: |
          cd build
          ctest --verbose
      - name: Upload coverage reports
        run: |
          pip install --user codecov
          codecov --gcov-root "${{ github.workspace }}/build" --gcov-exec gcov-10 --gcov-args "-s ${{ github.workspace }}"
