name: macOS
on:
  push:
    paths-ignore:
      - '.clang-tidy'
      - 'LICENSE'
      - 'README.md'
jobs:
  ci:
    name: macOS
    runs-on: macos-11
    strategy:
      matrix:
        include:
          - config: Release
          - config: Debug
      fail-fast: false
    env:
      CMAKE_GENERATOR: Ninja
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/build/_SeirDownloads
          key: macos-${{ hashFiles('cmake/SeirPackages/*.cmake') }}
      - name: Install prerequisites
        run: |
          brew install nasm ninja
      - name: Run CMake
        run: |
          export CXX=$(brew --prefix llvm)/bin/clang++
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/install" \
            -DSEIR_3RDPARTY_SKIP="nasm;zlib;zstd" \
            -DSEIR_APP=ON \
            -DSEIR_AUDIO_AULOS=OFF \
            -DSEIR_AUDIO_OGGVORBIS=OFF \
            -DSEIR_AUDIO_WAV=OFF \
            -DSEIR_BENCHMARKS=ON \
            -DSEIR_COMPRESSION_ZLIB=ON \
            -DSEIR_COMPRESSION_ZSTD=OFF \
            -DSEIR_EXAMPLES=ON \
            -DSEIR_IMAGE_BMP=ON \
            -DSEIR_IMAGE_ICO=ON \
            -DSEIR_IMAGE_JPEG=ON \
            -DSEIR_IMAGE_TGA=ON \
            -DSEIR_TESTS=ON \
            -DSEIR_U8MAIN=ON
      - name: Build
        run: |
          cmake --build build
      - name: Run tests
        run: |
          cd build
          ctest --verbose
      - name: Check exports
        run: |
          export CXX=$(brew --prefix llvm)/bin/clang++
          cmake --build build --target install
          cmake -S cmake/test -B build.test \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DCMAKE_PREFIX_PATH="${{ github.workspace }}/install"
          cmake --build build.test
