name: macOS
on:
  push:
    paths-ignore:
      - '.clang-tidy'
      - 'LICENSE'
      - 'README.md'
jobs:
  build:
    name: Build
    runs-on: macos-14
    strategy:
      matrix:
        include:
          - config: Release
          - config: Debug
      fail-fast: false
    env:
      CMAKE_GENERATOR: Ninja
      CURL_SSL_BACKEND: SecureTransport # https://gitlab.kitware.com/cmake/cmake/-/issues/25522
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/build/_SeirDownloads
          key: macos-${{ hashFiles('cmake/SeirPackages/*.cmake') }}
      - name: Install prerequisites
        run: |
          brew install ninja
      - name: Run CMake
        run: |
          export CC=$(brew --prefix llvm@15)/bin/clang
          export CXX=$(brew --prefix llvm@15)/bin/clang++
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/install" \
            -DSEIR_3RDPARTY_SKIP="freetype;jpeg;ogg;vorbis;zlib;zstd" \
            -DSEIR_AUDIO_OGGVORBIS=OFF \
            -DSEIR_AUDIO_WAV=OFF \
            -DSEIR_BENCHMARKS=ON \
            -DSEIR_COMPRESSION_ZLIB=ON \
            -DSEIR_COMPRESSION_ZSTD=OFF \
            -DSEIR_EXAMPLES=ON \
            -DSEIR_GUI=ON \
            -DSEIR_IMAGE_BMP=ON \
            -DSEIR_IMAGE_ICO=ON \
            -DSEIR_IMAGE_JPEG=ON \
            -DSEIR_IMAGE_TGA=ON \
            -DSEIR_RENDERER=Dummy \
            -DSEIR_SERIALIZATION=ON \
            -DSEIR_SYNTH=ON \
            -DSEIR_TESTS=ON \
            -DSEIR_U8MAIN=ON
      - name: Build
        run: |
          cmake --build build
      - name: Run tests
        run: |
          cd build
          ctest --verbose
      - name: Build usage examples
        run: |
          export CC=$(brew --prefix llvm@15)/bin/clang
          export CXX=$(brew --prefix llvm@15)/bin/clang++
          cmake -S examples/usage/cmake_fetchcontent -B build.cmake_fetchcontent \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DREPLACE_WITH_COMMIT_HASH=${{ github.sha }}
          cmake --build build.cmake_fetchcontent
          cmake --build build --target install
          cmake -S examples/usage/cmake_package -B build.cmake_package \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DCMAKE_PREFIX_PATH="${{ github.workspace }}/install"
          cmake --build build.cmake_package
