name: Windows
on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
jobs:
  ninja:
    name: Ninja
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - config: Release
          - config: Debug
      fail-fast: false
    env:
      CMAKE_GENERATOR: Ninja
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: Install prerequisites
        run: |
          cinst --no-progress ninja
      - name: Run CMake
        run: |
          cmake -S . -B build `
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} `
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}\install" `
            -DSEIR_AUDIO=ON `
            -DSEIR_AUDIO_AULOS=ON `
            -DSEIR_AUDIO_OGGVORBIS=ON `
            -DSEIR_AUDIO_WAV=ON `
            -DSEIR_BENCHMARKS=ON `
            -DSEIR_COMPRESSION_ZLIB=ON `
            -DSEIR_COMPRESSION_ZSTD=ON `
            -DSEIR_DATA=ON `
            -DSEIR_EXAMPLES=ON `
            -DSEIR_STATIC_RUNTIME=${{ matrix.config != 'Debug' && 'ON' || 'OFF' }} `
            -DSEIR_TESTS=ON `
            -DSEIR_U8MAIN=ON
      - name: Build
        run: |
          cmake --build build
      - name: Run tests
        run: |
          cd build
          ctest --verbose
      - name: Check exports
        run: |
          cmake --build build --target install
          cmake -S cmake\test -B build.test `
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} `
            -DCMAKE_PREFIX_PATH="${{ github.workspace }}\install" `
            -DSTATIC_RUNTIME=${{ matrix.config != 'Debug' && 'ON' || 'OFF' }}
          cmake --build build.test
  visual-studio:
    # This job builds the project from Visual Studio solution generated by CMake.
    # It ensures it is a valid way to build Seir.
    name: Visual Studio
    runs-on: windows-latest
    env:
      CMAKE_GENERATOR: Visual Studio 16 2019
      CMAKE_GENERATOR_PLATFORM: Win32
    steps:
      - uses: actions/checkout@v2
      - name: Run CMake
        run: |
          cmake -S . -B build `
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}\install" `
            -DSEIR_AUDIO=ON `
            -DSEIR_AUDIO_AULOS=ON `
            -DSEIR_AUDIO_OGGVORBIS=ON `
            -DSEIR_AUDIO_WAV=ON `
            -DSEIR_COMPRESSION_ZLIB=ON `
            -DSEIR_COMPRESSION_ZSTD=ON `
            -DSEIR_DATA=ON `
            -DSEIR_TESTS=ON
      - name: Build Debug
        run: |
          cmake --build build --config Debug --parallel -- /nologo
          cmake --build build --config Debug --target install -- /nologo
      - name: Build RelWithDebInfo
        run: |
          cmake --build build --config RelWithDebInfo --parallel -- /nologo
          cmake --build build --config RelWithDebInfo --target install -- /nologo
      - name: Run tests
        run: |
          cd build
          ctest --verbose --build-config Debug
