if(NOT TARGET plf_colony::plf_colony)
	get_filename_component(_path "${CMAKE_CURRENT_LIST_FILE}" PATH)
	get_filename_component(_path "${_path}" PATH)
	get_filename_component(_path "${_path}" PATH)
	get_filename_component(_path "${_path}" PATH)
	if(_path STREQUAL "/")
		set(_path "")
	endif()
	add_library(plf_colony::plf_colony INTERFACE IMPORTED)
	set_target_properties(plf_colony::plf_colony PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${_path}/include")
endif()
